//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bank.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bank.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Report
        ///1	Income Statement	RIAD4340
        ///2	Changes in Bank Equity Capital	RIAD3210
        ///3	Charge-offs and Recoveries on Loans and Leases
        ///3.a	Year-to-date Charge-offs	RIAD4635
        ///3.b	Year-to-date Recoveries	RIAD4605
        ///4	Changes in Allowance for Loan and Lease Losses	RIAD3123
        ///5	Disaggregated Data on the Allowance for Loan and Lease Losses
        ///5.a	Recorded Investment: Individually Evaluated for Impairment and Determined to be Impaired	RCONM746
        ///5.b	Allowance Balance: Individually Evaluated for Impairment and Determin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string form_41 {
            get {
                return ResourceManager.GetString("form_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Sheet
        ///1	Cash and balances due from depository institutions	
        ///1.a	Noninterest-bearing balances and currency and coin	RCON0081
        ///1.b	Interest-bearing balances	RCON0071
        ///2	Securities	
        ///2.a	Held-to-maturity securities	RCON1754
        ///2.b	Available-for-sale securities	RCON1773
        ///3	Federal funds sold and securities purchased under agreements to resell	
        ///3.a	Federal funds sold	RCONB987
        ///3.b	 Securities purchased under agreements to resell	RCONB989
        ///4	Loans and lease financing receivables	
        ///4.a	Loans and leases he [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string form_41_rc {
            get {
                return ResourceManager.GetString("form_41_rc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform Bank Performance Report - Summary Ratios
        ///1	Interest Income (TE)	UBPRE001
        ///1.a	Interest Expense	UBPRE002
        ///1.b	Net Interest Income (TE)	UBPRE003
        ///1.c	Noninterest Income	UBPRE004
        ///1.d	Noninterest Expense	UBPRE005.
        /// </summary>
        internal static string ubpr {
            get {
                return ResourceManager.GetString("ubpr", resourceCulture);
            }
        }
    }
}
